/**
 * The folder the lab was pointed at, if it was pointed at one.
 *
 * Generated by `vite-plugin-lab-screens` at request time: a glob has to be a
 * literal, so a folder chosen when the server starts cannot be one. The plugin
 * scans it and writes this module instead.
 */
declare module 'virtual:lab-screens' {
  /** The absolute path that was scanned, or null when none was given. */
  export const root: string | null;
  /** Keyed by path relative to that root, forward slashes. */
  export const pages: Record<string, { html: string; base: string }>;
}
