#!/usr/bin/env node
/**
 * Install the in-page tools and mount them on the canvas.
 *
 *   npm run lab:tools           install the latest of each and wire it up
 *   npm run lab:tools -- --off  unmount them again (leaves the packages)
 *
 * Three of these are components and mount once for the whole canvas, because
 * each works on a document and the canvas is one document — which is what
 * makes measuring *between* two frames possible at all. align-ui is a Vite
 * plugin rather than a component, so `vite-plugin-lab-tools.ts` picks it up
 * from the dev server instead. Nothing to edit either way.
 *
 * What this writes is `src/lab/tools/enabled.tsx`, generated and out of git.
 * That file is the switch.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const target = resolve(root, 'src/lab/tools/enabled.tsx');
const argv = process.argv.slice(2);

if (argv.includes('--off')) {
  if (existsSync(target)) {
    rmSync(target);
    process.stdout.write('\n  Tools unmounted. The packages are still installed.\n\n');
  } else {
    process.stdout.write('\n  Nothing was mounted.\n\n');
  }
  process.exit(0);
}

/**
 * What each one is, and what it needs.
 *
 * `react` is the major version the package requires, because one of them will
 * not mount on 18 and saying so beforehand beats a blank overlay. `spec` is
 * what npm is asked for, when that differs from the name.
 */
const TOOLS = [
  {
    pkg: 'align-ui',
    spec: 'github:ViShEsHK2412/align-ui',
    react: 0,
    plugin: true,
  },
  {
    pkg: 'agentation',
    react: 18,
    notice: 'PolyForm Shield 1.0.0 — usable, not vendorable',
    imports: "import { Agentation } from 'agentation';",
    mount: '<Agentation />',
  },
  {
    pkg: 'interface-kit',
    react: 19,
    imports: "import { InterfaceKit } from 'interface-kit/react';",
    mount: '<InterfaceKit />',
  },
  {
    pkg: 'dialkit',
    react: 18,
    imports: "import { DialRoot } from 'dialkit';",
    mount: '<DialRoot />',
  },
];

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const reactMajor = Number.parseInt(
  String(pkg.dependencies?.react ?? '0').replace(/[^\d]*(\d+).*/, '$1'),
  10,
);

const wanted = TOOLS.filter((t) => t.react <= reactMajor);
const skipped = TOOLS.filter((t) => t.react > reactMajor);

/*
 * Always install, never "install only what is missing".
 *
 * agentation and interface-kit move fast — twenty-odd releases between them in
 * a few months — and a rig that pins whatever it first saw is a rig that
 * quietly goes stale. align-ui is yours and changes more often than that.
 */
process.stdout.write(`\n  Installing ${wanted.map((t) => t.pkg).join(', ')}\n`);
for (const tool of wanted) {
  if (tool.notice) process.stdout.write(`  ${tool.pkg}: ${tool.notice}\n`);
}

const install = spawnSync(
  'npm',
  ['i', '-D', ...wanted.map((t) => t.spec ?? `${t.pkg}@latest`)],
  { cwd: root, stdio: 'inherit', shell: process.platform === 'win32' },
);
if (install.status !== 0) process.exit(install.status ?? 1);

for (const tool of skipped) {
  process.stdout.write(
    `\n  Skipping ${tool.pkg}: it needs React ${tool.react}+, this project is on ${reactMajor}.\n`,
  );
}

const mounted = wanted.filter((t) => !t.plugin);
const generated = [
  '/*',
  ' * Generated by `npm run lab:tools`. Not in git — delete it, or run',
  ' * `npm run lab:tools -- --off`, and the tools are gone again.',
  ' *',
  ' * Mounted once for the whole canvas, because every one of these works on a',
  ' * document and the canvas is a document. Measuring between two frames, or',
  ' * annotating ten variants in one pass, is what that arrangement buys and',
  ' * what an iframe per screen would have taken away.',
  ' */',
  ...mounted.map((t) => t.imports),
  '',
  'export function Tools() {',
  '  return (',
  '    <>',
  ...mounted.map((t) => `      ${t.mount}`),
  '    </>',
  '  );',
  '}',
  '',
];

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, generated.join('\n'), 'utf8');

const report = [
  '',
  `  On the canvas: ${mounted.map((t) => t.pkg).join(', ')}`,
  ...(wanted.some((t) => t.plugin)
    ? ['  In the dev server: align-ui, on Ctrl/Cmd + Shift + A (restart to pick it up)']
    : []),
  '',
  '  One inspector armed at a time, and measure at 100% zoom (Shift 0).',
  '  The canvas scales the page, so anything reading getBoundingClientRect off',
  '  a frame at 81% reports 81% of the truth. The HUD says so.',
  '',
  '',
];
process.stdout.write(report.join('\n'));
