#!/usr/bin/env node
/**
 * Install the in-page tools and mount them on the canvas.
 *
 *   npm run lab:tools           install what is missing and wire it up
 *   npm run lab:tools -- --off  unmount them again (leaves the packages)
 *
 * Each of these is an overlay that works on one document, and the canvas is
 * one document, so they mount once at lab level and reach every screen. What
 * this writes is `src/lab/tools/enabled.tsx`, which is generated and ignored
 * by git — the file is the switch.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const target = resolve(root, 'src/lab/tools/enabled.tsx');

const argv = process.argv.slice(2);

if (argv.includes('--off')) {
  if (existsSync(target)) {
    rmSync(target);
    process.stdout.write('\n  Tools unmounted. The packages are still installed.\n\n');
  } else {
    process.stdout.write('\n  Nothing was mounted.\n\n');
  }
  process.exit(0);
}

/**
 * What each one is, and what it needs.
 *
 * `react` is the version each package asks for, because one of them will not
 * mount on 18 and saying so beforehand is better than a blank overlay.
 */
const TOOLS = [
  {
    pkg: 'agentation',
    what: 'click an element, write a note, hand the agent a selector',
    react: 18,
    licence: 'PolyForm Shield 1.0.0 — usable, not vendorable',
    mount: '<Agentation />',
    imports: "import { Agentation } from 'agentation';",
  },
  {
    pkg: 'interface-kit',
    what: 'restyle an element live, copy the diff',
    react: 19,
    licence: 'MIT',
    mount: '<InterfaceKit />',
    imports: "import { InterfaceKit } from 'interface-kit/react';",
  },
  {
    pkg: 'dialkit',
    what: 'live controls and a timeline for values you declare',
    react: 18,
    licence: 'MIT',
    mount: '<DialRoot />',
    imports: "import { DialRoot } from 'dialkit';",
  },
];

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const installed = new Set([
  ...Object.keys(pkg.dependencies ?? {}),
  ...Object.keys(pkg.devDependencies ?? {}),
]);

const reactMajor = Number.parseInt(
  String(pkg.dependencies?.react ?? '0').replace(/[^\d]*(\d+).*/, '$1'),
  10,
);

const wanted = TOOLS.filter((t) => t.react <= reactMajor);
const skipped = TOOLS.filter((t) => t.react > reactMajor);
const missing = wanted.filter((t) => !installed.has(t.pkg));

if (missing.length > 0) {
  process.stdout.write(`\n  Installing ${missing.map((t) => t.pkg).join(', ')}\n`);
  for (const tool of missing) {
    if (tool.licence.startsWith('PolyForm')) {
      process.stdout.write(`  ${tool.pkg}: ${tool.licence}\n`);
    }
  }
  const run = spawnSync('npm', ['i', '-D', ...missing.map((t) => t.pkg)], {
    cwd: root,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
  if (run.status !== 0) process.exit(run.status ?? 1);
}

for (const tool of skipped) {
  process.stdout.write(
    `\n  Skipping ${tool.pkg}: it needs React ${tool.react}+, this project is on ${reactMajor}.\n`,
  );
}

const body = `/*
 * Generated by \`npm run lab:tools\`. Not in git — delete it, or run
 * \`npm run lab:tools -- --off\`, and the tools are gone again.
 *
 * Mounted once for the whole canvas, because every one of these works on a
 * document and the canvas is a document. Measuring between two frames, or
 * annotating ten variants in one pass, is the thing this arrangement buys and
 * an iframe per screen would take away.
 */
${wanted.map((t) => t.imports).join('\n')}

export function Tools() {
  return (
    <>
${wanted.map((t) => `      ${t.mount}`).join('\n')}
    </>
  );
}
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, body, 'utf8');

process.stdout.write(
  `\n  Mounted on the canvas: ${wanted.map((t) => t.pkg).join(', ')}\n`
  + '\n  align-ui is separate: it is a Vite plugin, one line in vite.config.ts.\n'
  + '      import align from \'align-ui/vite\';   plugins: [ ..., align() ]\n'
  + '\n  One inspector at a time, and measure at 100% zoom — Shift 0.\n'
  + '  The canvas scales the page, so anything reading getBoundingClientRect\n'
  + '  off a frame at 81% reports 81% of the truth.\n\n',
);
